### ISSUE TITLE
Compile Error on Linux

### ISSUE THREAD

**Issue by GarethJacobsNZ** [PerryWerneck/pw3270#3]
I get the following error compiling this application on 5.3.0-46-generic #38~18.04.1-Ubuntu SMP:

...
make[1]: Entering directory '/home/garlyn/mvs/download/pw3270/pw3270/src/libpw3270cpp'
session.cc ...
exception.cc ...
local.cc ...
remote.cc ...
remote.cc: In member function ‘virtual void h3270::remote::set_unlock_delay(short unsigned int)’:
remote.cc:1634:4: error: ‘set_intval’ was not declared in this scope; did you mean ‘query_intval’?
 1634 |    set_intval(HLLAPI_PACKET_SET_UNLOCK_DELAY,(int) ms);
      |    ^~~~~~~~~~
      |    query_intval
Makefile:108: recipe for target '.obj/Release/remote.o' failed
make[1]: *** [.obj/Release/remote.o] Error 1
make[1]: Leaving directory '/home/garlyn/mvs/download/pw3270/pw3270/src/libpw3270cpp'
Makefile:88: recipe for target '/home/garlyn/mvs/download/pw3270/pw3270/.bin/Release/libpw3270cpp.a' failed

Please let me know if you need further.

Gareth

**Comment by PerryWerneck** [comment]
Can you test if this problem happens with the "develop" branch?

**Comment by PerryWerneck** [comment]
The method set_intval wasn't defined in non-dbus builds.
