### ISSUE TITLE
When calling pw3270, the following error occurs: System-Linux:~$ pw3270 GLib-GIO _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’ gtk Loading plugins from /usr/lib/pw3270-plugins GLib unsetenv() is not thread-safe and should not be used after threads are created GLib-GIO _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’ gtk Adding '/usr/share/pw3270/icons' on icon search path lib3270 Invalid revision 20210928 when setting callback table gtk Tabela de callbacks inválida, a revisão 20220412 da lib3270 não pode ser usada (esperando a revisão 20210928) Trace/breakpoint trap (imagem do núcleo gravada)

### ISSUE THREAD

**Issue by Hiperiao** [PerryWerneck/pw3270#35]
## Describe the Bug
Error message on application startup:
`Tabela de callbacks inválida, a revisão 20220412 da lib3270 não pode ser usada (esperando a revisão 20210928) Trace/breakpoint trap (imagem do núcleo gravada)
`
## Expected Behavior
Normal application start

## System
_Please complete the following information:_
 - OS Name and version XUbuntu 20.04
 - PW3270 version and architecture NOT-INFORMED

**Comment by Hiperiao** [comment]
OS Name and version: XUbuntu 20.04

**Comment by PerryWerneck** [comment]
By the message 'Tabela de callbacks inválida, a revisão 20220412 da lib3270 não pode ser usada (esperando a revisão 20210928) Trace/breakpoint trap (imagem do núcleo gravada)' there's a version mismatch in the system. What are the versions of the installed package lib3270-unstable?

**Comment by PerryWerneck** [comment]
Rebuild application and updated from repository, after that is starts without error.
